<?xml version="1.0" encoding="UTF-8"?>
<pd:ProcessDefinition xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ns="http://www.tibco.com/pe/EngineTypes" xmlns:pfx0="http://www.tibco.com/CommonLE2/namespace/Public/Pluggable/GUI/Configuration/Type" xmlns:pfx1="http://www.tibco.com/CommonLE2/namespace/private/Common" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdlPfx="http://www.tibco.com/CommonLE2/namespace/Administration/GUIServices/Type" xmlns:ns12="http://www.tibco.com/CommonLE/namespace/Common" xmlns:pfx="http://www.tibco.com/pe/DeployedVarsType" xmlns:pd="http://xmlns.tibco.com/bw/process/2003" xmlns:ns2="http://www.tibco.com/CommonLE2/namespace/Administration/GUIServices/Category" xmlns:ns1="http://www.tibco.com/pe/GenerateErrorActivity/InputSchema" xmlns:ns4="http://www.tibco.com/CommonLE2/Private/Administration" xmlns:ns3="http://www.tibco.com/CommonLE2/Public/Common">
    <wsdl:import namespace="http://www.tibco.com/CommonLE2/namespace/Administration/GUIServices/Type" location="/SharedResources/WSDL/GUI/Administration/intfUpdateType.wsdl"/>
    <pd:name>Administration/GUIServices/TypeServices/wsCreateType.process</pd:name>
    <pd:startName>Start</pd:startName>
    <pd:startType wsMsgRef="wsdlPfx:ExceptionTypes"/>
    <pd:startX>150</pd:startX>
    <pd:startY>50</pd:startY>
    <pd:returnBindings>
        <wsdlPfx:Dummy/>
    </pd:returnBindings>
    <pd:endName>End</pd:endName>
    <pd:endType wsMsgRef="wsdlPfx:Dummy"/>
    <pd:endX>450</pd:endX>
    <pd:endY>50</pd:endY>
    <pd:errorSchemas>
        <Schema1 wsMsgRef="wsdlPfx:Error"/>
    </pd:errorSchemas>
    <pd:processVariables/>
    <pd:targetNamespace>http://xmlns.example.com/1285818194398</pd:targetNamespace>
    <pd:activity name="Create Type">
        <pd:type>com.tibco.pe.core.CallProcessActivity</pd:type>
        <pd:resourceType>ae.process.subprocess</pd:resourceType>
        <pd:x>272</pd:x>
        <pd:y>50</pd:y>
        <config>
            <processName>/Administration/DataAccess/Type/Oracle/CreateType.process</processName>
            <processNameXPath>concat('/Administration/DataAccess/Type/',$_globalVariables/pfx:GlobalVariables/Database/MIG_DatabaseType,'/CreateType.process')</processNameXPath>
        </config>
        <pd:inputBindings>
            <ns4:TypeUpdate>
                <ns4:ID>
                    <xsl:value-of select="$Start/wsdlPfx:ExceptionTypes/parameters/pfx0:ExceptionTypes/pfx0:ExceptionType[1]/pfx0:ApplicationID"/>
                </ns4:ID>
                <ns4:Name>
                    <xsl:value-of select="$Start/wsdlPfx:ExceptionTypes/parameters/pfx0:ExceptionTypes/pfx0:ExceptionType[1]/pfx0:TypeName"/>
                </ns4:Name>
                <ns4:Description>
                    <xsl:value-of select="$Start/wsdlPfx:ExceptionTypes/parameters/pfx0:ExceptionTypes/pfx0:ExceptionType[1]/pfx0:Description"/>
                </ns4:Description>
            </ns4:TypeUpdate>
        </pd:inputBindings>
    </pd:activity>
    <pd:activity name="Catch AppID Does Not Exist">
        <pd:type>com.tibco.pe.core.CatchActivity</pd:type>
        <pd:resourceType>ae.activities.catch</pd:resourceType>
        <pd:x>149</pd:x>
        <pd:y>149</pd:y>
        <pd:handler>true</pd:handler>
        <config>
            <fault>localname=ApplicationIDNotFound namespace=http://www.tibco.com/CommonLE2/namespace/private/Common</fault>
        </config>
        <pd:inputBindings/>
    </pd:activity>
    <pd:activity name="Generate Error">
        <pd:type>com.tibco.pe.core.GenerateErrorActivity</pd:type>
        <pd:resourceType>ae.activities.throw</pd:resourceType>
        <pd:x>311</pd:x>
        <pd:y>141</pd:y>
        <config>
            <faultName>Schema1</faultName>
        </config>
        <pd:inputBindings>
            <ns1:ActivityInput>
                <message>
                    <xsl:value-of select="$Catch-AppID-Does-Not-Exist/pfx1:ApplicationIDNotFound/pfx1:Message"/>
                </message>
                <messageCode>
                    <xsl:value-of select="$Catch-AppID-Does-Not-Exist/pfx1:ApplicationIDNotFound/pfx1:Code"/>
                </messageCode>
                <data>
                    <wsdlPfx:Error>
                        <parameters>
                            <ns3:Error>
                                <ns3:Message>
                                    <xsl:value-of select="$Catch-AppID-Does-Not-Exist/pfx1:ApplicationIDNotFound/pfx1:Message"/>
                                </ns3:Message>
                                <ns3:Code>
                                    <xsl:value-of select="$Catch-AppID-Does-Not-Exist/pfx1:ApplicationIDNotFound/pfx1:Code"/>
                                </ns3:Code>
                            </ns3:Error>
                        </parameters>
                    </wsdlPfx:Error>
                </data>
            </ns1:ActivityInput>
        </pd:inputBindings>
    </pd:activity>
    <pd:activity name="Catch All Errors">
        <pd:type>com.tibco.pe.core.CatchActivity</pd:type>
        <pd:resourceType>ae.activities.catch</pd:resourceType>
        <pd:x>144</pd:x>
        <pd:y>247</pd:y>
        <pd:handler>true</pd:handler>
        <config>
            <catchAll>true</catchAll>
        </config>
        <pd:inputBindings/>
    </pd:activity>
    <pd:activity name="Local Exception Handler">
        <pd:type>com.tibco.pe.core.CallProcessActivity</pd:type>
        <pd:resourceType>ae.process.subprocess</pd:resourceType>
        <pd:x>300</pd:x>
        <pd:y>252</pd:y>
        <config>
            <processName>/Common/Local Exception Handler.process</processName>
        </config>
        <pd:inputBindings>
            <ns12:Exception>
                <ErrorMessage>
                    <xsl:value-of select="$_error/ns:ErrorReport/Msg"/>
                </ErrorMessage>
                <ErrorCode>
                    <xsl:value-of select="$_error/ns:ErrorReport/MsgCode"/>
                </ErrorCode>
                <ns12:Error>
                    <xsl:for-each xmlns:xsl="http://www.w3.org/1999/XSL/Transform" select="$_error/ns:ErrorReport">
                        <ns12:ErrorReport>
                            <StackTrace>
                                <xsl:value-of select="StackTrace"/>
                            </StackTrace>
                            <Msg>
                                <xsl:value-of select="Msg"/>
                            </Msg>
                            <FullClass>
                                <xsl:value-of select="FullClass"/>
                            </FullClass>
                            <Class>
                                <xsl:value-of select="Class"/>
                            </Class>
                            <ProcessStack>
                                <xsl:value-of select="ProcessStack"/>
                            </ProcessStack>
                            <MsgCode>
                                <xsl:value-of select="MsgCode"/>
                            </MsgCode>
                        </ns12:ErrorReport>
                    </xsl:for-each>
                </ns12:Error>
            </ns12:Exception>
        </pd:inputBindings>
    </pd:activity>
    <pd:activity name="Generate Internal Error">
        <pd:type>com.tibco.pe.core.GenerateErrorActivity</pd:type>
        <pd:resourceType>ae.activities.throw</pd:resourceType>
        <pd:x>452</pd:x>
        <pd:y>252</pd:y>
        <config>
            <faultName>Schema1</faultName>
        </config>
        <pd:inputBindings>
            <ns1:ActivityInput>
                <message>
                    <xsl:value-of select="$_error/ns:ErrorReport/Msg"/>
                </message>
                <messageCode>
                    <xsl:value-of select="$_error/ns:ErrorReport/MsgCode"/>
                </messageCode>
                <data>
                    <wsdlPfx:Error>
                        <parameters>
                            <ns3:Error>
                                <ns3:Message>
                                    <xsl:value-of select="$_error/ns:ErrorReport/Msg"/>
                                </ns3:Message>
                                <ns3:Code>
                                    <xsl:value-of select="$_error/ns:ErrorReport/MsgCode"/>
                                </ns3:Code>
                            </ns3:Error>
                        </parameters>
                    </wsdlPfx:Error>
                </data>
            </ns1:ActivityInput>
        </pd:inputBindings>
    </pd:activity>
    <pd:transition>
        <pd:from>Start</pd:from>
        <pd:to>Create Type</pd:to>
        <pd:lineType>Default</pd:lineType>
        <pd:lineColor>-16777216</pd:lineColor>
        <pd:conditionType>always</pd:conditionType>
    </pd:transition>
    <pd:transition>
        <pd:from>Create Type</pd:from>
        <pd:to>End</pd:to>
        <pd:lineType>Default</pd:lineType>
        <pd:lineColor>-16777216</pd:lineColor>
        <pd:conditionType>always</pd:conditionType>
    </pd:transition>
    <pd:transition>
        <pd:from>Catch AppID Does Not Exist</pd:from>
        <pd:to>Generate Error</pd:to>
        <pd:lineType>Default</pd:lineType>
        <pd:lineColor>-16777216</pd:lineColor>
        <pd:conditionType>always</pd:conditionType>
    </pd:transition>
    <pd:transition>
        <pd:from>Catch All Errors</pd:from>
        <pd:to>Local Exception Handler</pd:to>
        <pd:lineType>Default</pd:lineType>
        <pd:lineColor>-16777216</pd:lineColor>
        <pd:conditionType>always</pd:conditionType>
    </pd:transition>
    <pd:transition>
        <pd:from>Local Exception Handler</pd:from>
        <pd:to>Generate Internal Error</pd:to>
        <pd:lineType>Default</pd:lineType>
        <pd:lineColor>-16777216</pd:lineColor>
        <pd:conditionType>always</pd:conditionType>
    </pd:transition>
</pd:ProcessDefinition>